/* Created by LockPlus Pro by JunesiPhone http://twitter.com/junesiphone */ 

var savedElements = {
    "placedElements":{
        "clock":{
            "font-family":"sanfranreg",
            "z-index":2,
            "color":"white",
            "position":"absolute",
            "font-size":"48px",
            "top":31,
            "left":"143px",
            "width":"151px",
            "height":"70px",
            "-webkit-transform":"rotate(0deg)",
            "text-align":"right"
        },
        "datestring":{
            "font-family":"sanfranreg",
            "z-index":2,
            "color":"white",
            "position":"absolute",
            "font-size":"8px",
            "top":83,
            "left":"149px",
            "width":"142px",
            "height":"13px",
            "-webkit-transform":"rotate(0deg)",
            "text-align":"right",
            "font-weight":"bold",
            "letter-spacing":"initial"
        },
        "icon":{
            "position":"absolute",
            "top":"40px",
            "left":"87px",
            "width":"53px",
            "height":"53px"
        },
        "temp":{
            "font-family":"sanfranreg",
            "z-index":2,
            "color":"white",
            "position":"absolute",
            "font-size":"35px",
            "top":34,
            "left":"26px",
            "width":"47px",
            "height":"43px",
            "-webkit-transform":"rotate(0deg)",
            "font-weight":"normal",
            "letter-spacing":"initial"
        },
        "condition":{
            "font-family":"sanfranreg",
            "z-index":2,
            "color":"white",
            "position":"absolute",
            "font-size":"8px",
            "top":72,
            "left":"28px",
            "width":"98px",
            "height":"10px",
            "-webkit-transform":"rotate(0deg)",
            "font-weight":"bold",
            "letter-spacing":"initial"
        },
        "rain":{
            "font-family":"sanfranreg",
            "z-index":2,
            "color":"white",
            "position":"absolute",
            "font-size":"8px",
            "top":83,
            "left":"52px",
            "width":"28px",
            "height":"10px",
            "-webkit-transform":"rotate(0deg)",
            "font-weight":"bold",
            "letter-spacing":"initial"
        },
        "textOne":{
            "font-family":"sanfranreg",
            "z-index":2,
            "color":"white",
            "position":"absolute",
            "font-size":"8px",
            "top":83,
            "left":"28px",
            "width":"30px",
            "innerHTML":"Rain:",
            "font-weight":"bold",
            "letter-spacing":"initial"
        }
    },
    "iconName":"perfect"
}